controllers/CourseController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Course;
use app\models\CourseSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\web\ForbiddenHttpException;
use yii\web\Response;

/**
 * Управляет работой с курсами
 *
 * @package app\controllers
 */
class CourseController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors(){
        return [
            'access' => [
                'class' => \yii\filters\AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['index', 'view', 'create', 'update', 'delete', 'restore'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
        ];
    }

    /**
     * Отображает список курсов
     *
     * @return string
     * @throws ForbiddenHttpException
     */
    public function actionIndex()
    {
        if (!Yii::$app->user->can('listCourses')) {
            throw new ForbiddenHttpException('Недостаточно прав');
        }
        $searchModel = new CourseSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', compact('searchModel','dataProvider'));
    }

    /**
     * Отображает страницу просмотра курса
     *
     * @param integer $id
     * @return string
     * @throws NotFoundHttpException|ForbiddenHttpException
     */
    public function actionView($id)
    {
        $model = $this->findModel($id);
        if (!Yii::$app->user->can('viewCourse')) {
            throw new ForbiddenHttpException('Недостаточно прав');
        }
        return $this->render('view', [
            'model' => $model,
        ]);
    }

    /**
     * Отображает страницу создания курса
     *
     * @return string|Response
     * @throws ForbiddenHttpException
     */
    public function actionCreate()
    {
        if (!Yii::$app->user->can('createCourse')) {
            throw new ForbiddenHttpException('Недостаточно прав');
        }
        $model = new Course();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Отображает страницу редактирования курса
     *
     * @param integer $id
     * @return string|Response
     * @throws NotFoundHttpException|ForbiddenHttpException
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if (!Yii::$app->user->can('updateCourse')) {
            throw new ForbiddenHttpException('Недостаточно прав');
        }
        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Удаляет курс
     *
     * @return Response
     * @throws NotFoundHttpException|ForbiddenHttpException
     */
    public function actionDelete()
    {
        if (!Yii::$app->user->can('deleteCourse')) {
            throw new ForbiddenHttpException('Недостаточно прав');
        }
        $id = Yii::$app->request->post('id');
        $course = $this->findModel($id);

        if (!$course->deleted) {
            $course->deleted = true;
            if (!$course->save()) {
                Yii::$app->session->setFlash('error', 'Во время удаления произошла ошибка');
            } else {
                Yii::$app->session->setFlash('success', 'Курс успешно удален');
            }
        }

        return Yii::$app->response->redirect(Yii::$app->request->referrer ? Yii::$app->request->referrer : '/courses');
    }

    /**
     * Восстанавливает курс
     *
     * @return Response
     * @throws NotFoundHttpException|ForbiddenHttpException
     */
    public function actionRestore()
    {
        if (!Yii::$app->user->can('restoreCourse')) {
            throw new ForbiddenHttpException('Недостаточно прав');
        }
        $id = Yii::$app->request->post('id');
        $group = $this->findModel($id);

        if ($group->deleted) {
            $group->deleted = false;
            if (!$group->save()) {
                Yii::$app->session->setFlash('error', 'Во время восстановления произошла ошибка');
            } else {
                Yii::$app->session->setFlash('success', 'Курс успешно восстановлен');
            }
        }

        return Yii::$app->response->redirect(Yii::$app->request->referrer ? Yii::$app->request->referrer : '/courses');
    }

    /**
     * Ищет курс по id
     *
     * @param integer $id
     * @return Course
     * @throws NotFoundHttpException
     */
    protected function findModel($id)
    {
        if (($model = Course::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('Страница не найдена.');
    }
}

controllers/GroupController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Group;
use app\models\GroupSearch;
use app\models\Student;
use yii\web\Controller;
use yii\web\Response;
use yii\web\NotFoundHttpException;
use yii\web\ForbiddenHttpException;
use yii\data\ActiveDataProvider;

/**
 * GroupController implements the CRUD actions for Group model.
 */
class GroupController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors(){
        return [
            'access' => [
                'class' => \yii\filters\AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['index', 'view', 'create', 'update', 'delete', 'restore'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
        ];
    }

    /**
     * Отображает список групп
     *
     * @return string
     * @throws ForbiddenHttpException
     */
    public function actionIndex()
    {
        if (!Yii::$app->user->can('listGroups')) {
            throw new ForbiddenHttpException('Недостаточно прав');
        }
        $searchModel = new GroupSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Отображает группу по id
     *
     * @param integer $id
     * @return string
     * @throws NotFoundHttpException|ForbiddenHttpException
     */
    public function actionView($id)
    {
        $model = $this->findModel($id);
        if (!Yii::$app->user->can('viewGroup', ['group' => $model])) {
            throw new ForbiddenHttpException('Недостаточно прав');
        }
        $dataGroupStudents = new ActiveDataProvider([
            'query' => Student::find()->where(['group_id' => $id]),
        ]);

        return $this->render('view', [
            'model' => $model,
            'dataGroupStudents' => $dataGroupStudents,
        ]);
    }

    /**
     * Создает новую группу
     *
     * @return string|Response
     * @throws \yii\db\Exception|ForbiddenHttpException
     */
    public function actionCreate()
    {
        if (!Yii::$app->user->can('createGroup')) {
            throw new ForbiddenHttpException('Недостаточно прав');
        }
        $model = new Group();
        $dataFreeStudents = new ActiveDataProvider([
            'query' => Student::find()->where(['group_id' => NULL]),
        ]);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            if ($model->setGroups(Yii::$app->request->post('students'), $model->id)) {
                return $this->redirect(['view', 'id' => $model->id]);
            }
        }

        return $this->render('create', [
            'model' => $model,
            'dataFreeStudents' => $dataFreeStudents,
        ]);
    }

    /**
     * Обновляет существующую группу
     *
     * @param integer $id
     * @return string|Response
     * @throws NotFoundHttpException|ForbiddenHttpException
     * @throws \yii\db\Exception
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if (!Yii::$app->user->can('updateGroup')) {
            throw new ForbiddenHttpException('Недостаточно прав');
        }

        $dataGroupStudents = new ActiveDataProvider([
            'query' => Student::find()->where(['group_id' => $id]),
        ]);
        $dataFreeStudents = new ActiveDataProvider([
            'query' => Student::find()->where(['group_id' => NULL]),
        ]);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            if ($model->setGroups(Yii::$app->request->post('studentGroup'), 'null')
                && $model->setGroups(Yii::$app->request->post('newStudent'), $model->id)) {
                return $this->redirect(['view', 'id' => $model->id]);
            }
        }

        return $this->render('update', [
            'model' => $model,
            'dataFreeStudents' => $dataFreeStudents,
            'dataGroupStudents' => $dataGroupStudents,
        ]);
    }

    /**
     * Удаляет группу
     *
     * @return Response
     * @throws NotFoundHttpException|ForbiddenHttpException
     */
    public function actionDelete()
    {
        if (!Yii::$app->user->can('deleteGroup')) {
            throw new ForbiddenHttpException('Недостаточно прав');
        }
        $id = Yii::$app->request->post('id');
        $group = $this->findModel($id);

        if (!$group->deleted) {
            $group->deleted = true;
            if (!$group->save()) {
                Yii::$app->session->setFlash('error', 'Во время удаления произошла ошибка');
            } else {
                Yii::$app->session->setFlash('success', 'Группа успешно удалена');
            }
        }

        return Yii::$app->response->redirect(Yii::$app->request->referrer ? Yii::$app->request->referrer : '/groups');
    }

    /**
     * Восстанавливает группу
     *
     * @return Response
     * @throws NotFoundHttpException|ForbiddenHttpException
     */
    public function actionRestore()
    {
        if (!Yii::$app->user->can('restoreGroup')) {
            throw new ForbiddenHttpException('Недостаточно прав');
        }
        $id = Yii::$app->request->post('id');
        $group = $this->findModel($id);

        if ($group->deleted) {
            $group->deleted = false;
            if (!$group->save()) {
                Yii::$app->session->setFlash('error', 'Во время восстановления произошла ошибка');
            } else {
                Yii::$app->session->setFlash('success', 'Группа успешно восстановлена');
            }
        }

        return Yii::$app->response->redirect(Yii::$app->request->referrer ? Yii::$app->request->referrer : '/groups');
    }

    /**
     * Ищет группу по id
     *
     * @param integer $id
     * @return Group
     * @throws NotFoundHttpException
     */
    protected function findModel($id)
    {
        if (($model = Group::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('Страница не найдена.');
    }
}

controllers/UserController.php
<?php

namespace app\controllers;

use app\models\User;
use app\models\UserSearch;
use app\models\UserForm;
use yii\data\ActiveDataProvider;
use yii\web\NotFoundHttpException;
use yii\web\ForbiddenHttpException;
use yii\web\Response;
use Yii;

/**
 * Управляет работой с пользователями
 *
 * @package app\controllers
 */
class UserController extends \yii\web\Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors(){
        return [
            'access' => [
                'class' => \yii\filters\AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['index', 'view', 'create', 'update', 'delete', 'restore'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
        ];
    }

    /**
     * Отображает список пользователей
     *
     * @return string
     * @throws ForbiddenHttpException
     */
    public function actionIndex()
    {
        if (!Yii::$app->user->can('listUsers')) {
            throw new ForbiddenHttpException('Недостаточно прав');
        }
        $searchModel = new UserSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', compact('dataProvider', 'searchModel'));
    }

    /**
     * Отображает страницу создания пользователя
     *
     * @return string|Response
     * @throws \yii\base\Exception
     */
    public function  actionCreate()
    {
        if (!Yii::$app->user->can('createUser')) {
            throw new ForbiddenHttpException('Недостаточно прав');
        }
        $userForm = new UserForm(['scenario' => UserForm::SCENARIO_CREATE]);
        $userForm->defaultType();
        if ($userForm->load(Yii::$app->request->post()) && $userForm->create()) {
            Yii::$app->session->setFlash('success', 'Пользователь успешно создан');
            return Yii::$app->response->redirect('/users');
        }
        return $this->render('create', ['userForm' => $userForm]);
    }

    /**
     * Отображает страницу с информацией о пользователе
     *
     * @param $id
     * @return string
     * @throws ForbiddenHttpException|NotFoundHttpException
     */
    public function actionView($id)
    {
        $model = $this->findModel($id);

        if (!Yii::$app->user->can('viewUser', ['user' => $model])) {
            throw new ForbiddenHttpException('Недостаточно прав');
        }
        $dataProvider = null;

        if ($model->type == 'student') {
            $dataProvider = new ActiveDataProvider([
                'query' => $model->students->getAttendances()
            ]);
        }


        return $this->render('view', [
            'model' => $model,
            'dataProvider' => $dataProvider
        ]);
    }

    /**
     * Отображает страницу редактирования пользователя
     *
     * @param $id
     * @return string|Response
     * @throws \yii\base\Exception
     */
    public function actionUpdate($id)
    {
        $userForm = new UserForm(['id' => $id, 'scenario' => UserForm::SCENARIO_UPDATE]);
        if (!Yii::$app->user->can('updateUser', ['user' => $userForm])) {
            throw new ForbiddenHttpException('Недостаточно прав');
        }
        if ($userForm->load(Yii::$app->request->post()) && $userForm->update()) {
            Yii::$app->session->setFlash('success', 'Пользователь успешно изменен');
            return Yii::$app->response->redirect("/user/$id");
        }

        return $this->render('update', ['userForm' => $userForm]);
    }

    /**
     * Удаляет пользователя
     *
     * @return Response
     * @throws ForbiddenHttpException|NotFoundHttpException
     */
    public function actionDelete()
    {
        if (!Yii::$app->user->can('deleteUser')) {
            throw new ForbiddenHttpException('Недостаточно прав');
        }
        $id = Yii::$app->request->post('id');
        $user = $this->findModel($id);

        if (!$user->deleted) {
            $user->deleted = true;
            if (!$user->save()) {
                Yii::$app->session->setFlash('error', 'Во время удаления произошла ошибка');
            } else {
                Yii::$app->session->setFlash('success', 'Пользователь успешно удален');
            }
        }

        return Yii::$app->response->redirect(Yii::$app->request->referrer ? Yii::$app->request->referrer : '/users');
    }

    /**
     * Восстанавливает пользователя
     *
     * @return Response
     * @throws ForbiddenHttpException|NotFoundHttpException
     */
    public function actionRestore()
    {
        if (!Yii::$app->user->can('restoreUser')) {
            throw new ForbiddenHttpException('Недостаточно прав');
        }
        $id = Yii::$app->request->post('id');
        $user = $this->findModel($id);

        if ($user->deleted) {
            $user->deleted = false;
            if (!$user->save()) {
                Yii::$app->session->setFlash('error', 'Во время восстановления произошла ошибка');
            } else {
                Yii::$app->session->setFlash('success', 'Пользователь успешно восстановлен');
            }
        }

        return Yii::$app->response->redirect(Yii::$app->request->referrer ? Yii::$app->request->referrer : '/users');
    }


    /**
     * Ищет пользователя по id
     *
     * @param integer $id
     * @return User
     * @throws NotFoundHttpException
     */
    protected function findModel($id)
    {
        if (($model = User::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('Страница не найдена.');
    }
}

views/group/_form.php
<?php

use yii\helpers\Html;
use yii\helpers\ArrayHelper;
use yii\widgets\ActiveForm;
use app\models\Course;

/* @var $this yii\web\View */
/* @var $model app\models\Group */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="group-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'name')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'course_id')->dropDownList(ArrayHelper::map(Course::find()->all(), 'id', function ($data) {
        return $data['name'];
    })) ?>

    <div class="form-group">
        <?= Html::submitButton('Сохранить', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/group/_studentsList.php
<?php

use yii\grid\GridView;
use yii\helpers\Html;
use yii\helpers\Url;

/* @var $this yii\web\View */
/* @var $model app\models\Group */
/* @var $form yii\widgets\ActiveForm */
/* @var $dataProvider yii\data\ActiveDataProvider */
/* @var $update boolean */
/* @var $listName string */

echo GridView::widget([
    'dataProvider' => $dataProvider,
    'layout' => "{items}",
    'columns' => [
        [
            'class' => 'yii\grid\SerialColumn',
            'headerOptions' => ['width' => '30'],
        ],
        $update ? [
            'class' => 'yii\grid\CheckboxColumn',
            'checkboxOptions' => function ($model) {
                return ['value' => $model->user_id];
            },
            'name' => $listName,
            'headerOptions' => ['width' => '30'],
        ] : ['visible' => false],
        [
            'label' => 'ФИО',
            'value' => function ($model) {
                return Html::a($model->getFullName(), Url::to(['user/view', 'id' => $model->user_id]));
            },
            'format' => 'raw'
        ],
    ],
]);

views/group/create.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\helpers\ArrayHelper;
use app\models\Course;


/* @var $this yii\web\View */
/* @var $model app\models\Group */
/* @var $dataFreeStudents yii\data\ActiveDataProvider */

$this->title = 'Новая группа';
$this->params['breadcrumbs'][] = ['label' => 'Группы', 'url' => ['/groups']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="group-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="col-lg-5">

        <?php $form = ActiveForm::begin(); ?>

        <?= $form->field($model, 'name')->textInput(['maxlength' => true]) ?>

        <?= $form->field($model, 'course_id')->dropDownList(ArrayHelper::map(Course::find()->all(), 'id', function ($data) {
            return $data['name'];
        })) ?>

        <?= $this->render('_studentsList', [
            'dataProvider' => $dataFreeStudents,
            'update' => 'false',
            'listName' => 'students',
        ]) ?>

        <?= Html::submitButton('Создать группу', ['class' => 'btn btn-success']) ?>

        <?php ActiveForm::end(); ?>

    </div>

</div>

views/group/index.php
<?php

use yii\helpers\Url;
use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel app\models\GroupSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Группы';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="group-index">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Yii::$app->user->can('createGroup') ? (
            Html::a('Создать группу', ['create'], ['class' => 'btn btn-success'])
        ) : '' ?>
    </p>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'rowOptions' => function ($model) {
            if ($model->deleted)
            {
                return ['class'=>'danger'];
            }
        },
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],
            'id',
            'name',
            'courseName',
            [
                'class' => 'yii\grid\ActionColumn',
                'header'=>'Действия',
                'headerOptions' => ['width' => '80'],
                'template' => (Yii::$app->user->can('viewGroup') ? '{view} ' : '')
                    . (Yii::$app->user->can('updateGroup') ? '{update} ' : ' ')
                    . (Yii::$app->user->can('deleteGroup') ? '{delete}' : ''),
                'buttons' => [
                    'delete' => function ($url, $model) {
                        return Html::a('<span class="glyphicon glyphicon-trash"></span>', Url::to(['group/delete']), [
                            'data' => [
                                'confirm' => 'Вы действительно хотите удалить группу?',
                                'method' => 'post',
                                'params' => [
                                    'id' => $model->id,
                                ],
                            ],
                        ]);
                    },
                ],
            ],
        ],
    ]); ?>

</div>

views/group/update.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\helpers\ArrayHelper;
use app\models\Course;

/* @var $this yii\web\View */
/* @var $model app\models\Group */

/* @var $form yii\widgets\ActiveForm */

/* @var $dataFreeStudents yii\data\ActiveDataProvider */
/* @var $dataGroupStudents yii\data\ActiveDataProvider */

$this->title = 'Редактирование группы: ' . $model->name;
$this->params['breadcrumbs'][] = ['label' => 'Группы', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->name, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Редактирование';
?>
<div class="group-update">

    <h1><?= Html::encode($this->title) ?></h1>
    <p>
        <?= Html::submitButton('Сохранить', ['class' => 'btn btn-success']) ?>
    </p>

        <?php $form = ActiveForm::begin(); ?>

        <div class="col-lg-12">

            <div class="col-lg-5">

                <?= $form->field($model, 'name')->textInput(['maxlength' => true]) ?>

            </div>

            <div class="col-lg-5">

                <?= $form->field($model, 'course_id')->dropDownList(ArrayHelper::map(Course::find()->all(), 'id', function ($data) {
                    return $data['name'];
                })) ?>

            </div>

        </div>

        <div class="col-lg-12">

            <div class="col-lg-5">

                <h3>Студенты группы</h3>

                <?= $this->render('_studentsList', [
                    'dataProvider' => $dataGroupStudents,
                    'update' => true,
                    'listName' => 'studentGroup',
                ]) ?>

            </div>

            <div class="col-lg-5">

                <h3>Свободные студенты</h3>

                <?= $this->render('_studentsList', [
                    'dataProvider' => $dataFreeStudents,
                    'update' => true,
                    'listName' => 'newStudent',
                ]) ?>

            </div>

        </div>

    <?php ActiveForm::end(); ?>

</div>

views/group/view.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\DetailView;
use yii\data\ActiveDataProvider;

/* @var $this yii\web\View */
/* @var $model app\models\Group */
/* @var $dataGroupStudents ActiveDataProvider */

$this->title = $model->name;
Yii::$app->user->can('listGroups') ? $this->params['breadcrumbs'][] = ['label' => 'Группы', 'url' => ['index']] : null ;
$this->params['breadcrumbs'][] = $this->title;
\yii\web\YiiAsset::register($this);
?>
<div class="group-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= $model->deleted ? Html::tag('h3', 'Группа удалена', ['style' => ['color' => 'red']])  : '' ?>
        <?= Yii::$app->user->can('updateGroup') ? (
            Html::a('Редактировать', ['update', 'id' => $model->id], ['class' => 'btn btn-primary'])
        ) : '' ?>
        <?= $model->deleted ? (
            Yii::$app->user->can('restoreGroup') ? (
                Html::a('Восстановить', ['restore'], [
                    'class' => 'btn btn-success',
                    'data' => [
                        'confirm' => 'Вы действительно хотите восстановить группу?',
                        'method' => 'post',
                        'params' => [
                            'id' => $model->id,
                        ],
                    ],
                ])
            ) : '') : (
            Yii::$app->user->can('deleteGroup') ? (
                Html::a('Удалить', ['delete'], [
                    'class' => 'btn btn-danger',
                    'data' => [
                        'confirm' => 'Вы действительно хотите удалить группу?',
                        'method' => 'post',
                        'params' => [
                            'id' => $model->id,
                        ],
                    ],
                ])
            ): '' ) ?>
        <?= Yii::$app->user->can('createAttendance', ['group' => $model, 'createAttendance' => true]) ? (
            Html::a('Отметить посещаемость', ['attendance/create'], [
                'class' => 'btn btn-success',
                'data' => [
                    'method' => 'post',
                    'params' => [
                        'groupId' => $model->id,
                    ],
                ],
            ])
        ) : '' ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'name',
            [
                'label' => 'Курс',
                'value' => Html::a($model->courses->name, Url::to(['course/view', 'id' => $model->course_id])),
                'format' => 'raw'
            ],
        ],
    ]) ?>

    <div>

        <h3>Студенты группы</h3>

        <?= $this->render('_studentsList', [
            'dataProvider' => $dataGroupStudents,
            'update' => false,
        ]) ?>

    </div>

</div>