models/User.php
<?php

namespace app\models;

use Yii;
use yii\base\NotSupportedException;
use yii\db\ActiveRecord;

/**
 * This is the model class for table "users".
 *
 * @property int $id
 * @property string $username
 * @property string $auth_key
 * @property string $password
 * @property string $type
 * @property bool $deleted
 *
 * @property Student $students
 * @property Educator $educators
 */
class User extends ActiveRecord implements \yii\web\IdentityInterface
{
    /** @var string  */
    const STUDENT_TYPE = 'student';
    /** @var string  */
    const EDUCATOR_TYPE = 'educator';

    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'users';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['username', 'auth_key', 'password'], 'required'],
            [['type'], 'string'],
            [['username'], 'string', 'max' => 20],
            [['auth_key'], 'string', 'max' => 32],
            [['password'], 'string', 'max' => 256],
            [['username'], 'unique'],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'username' => 'Имя пользователя',
            'auth_key' => 'Auth Key',
            'password' => 'Пароль',
            'type' => 'Тип пользователя',
            'fullName' => 'ФИО'
        ];
    }

    public function getFullName()
    {
        if ($this->type == 'student') {
            return $this->students->getFullName();
        }
        return $this->educators->getFullName();
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getStudents()
    {
        return $this->hasOne(Student::className(), ['user_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getEducators()
    {
        return $this->hasOne(Educator::className(), ['user_id' => 'id']);
    }

    /**
     * {@inheritdoc}
     */
    public static function findIdentity($id)
    {
        return static::findOne($id);
    }

    /**
     * Возвращает кол-во записей
     *
     * @param null $params
     * @return int|string
     */
    public static function getCount($params = null)
    {
        return static::find()->Where($params)->count();
    }

    /**
     * {@inheritdoc}
     * @throws NotSupportedException
     */
    public static function findIdentityByAccessToken($token, $type = null)
    {
        throw new NotSupportedException('"findIdentityByAccessToken" is not implemented.');
    }

    /**
     * Finds user by username
     *
     * @param string $username
     * @return static|null
     */
    public static function findByUsername($username)
    {
        return static::findOne(['username' => $username]);
    }

    /**
     * {@inheritdoc}
     */
    public function getId()
    {
        return $this->getPrimaryKey();
    }

    /**
     * {@inheritdoc}
     */
    public function getAuthKey()
    {
        return $this->auth_key;
    }

    /**
     * {@inheritdoc}
     */
    public function validateAuthKey($authKey)
    {
        return $this->getAuthKey() === $authKey;
    }

    /**
     * Validates password
     *
     * @param string $password password to validate
     * @return bool if password provided is valid for current user
     */
    public function validatePassword($password)
    {
        return Yii::$app->security->validatePassword($password, $this->password);
    }

    /**
     * Sets a hashed password
     *
     * @param $password string
     * @throws \yii\base\Exception
     */
    public function setPassword($password)
    {
        $this->password = Yii::$app->security->generatePasswordHash($password);
    }

    /**
     * Генерирует токен
     *
     * @throws \yii\base\Exception
     */
    public function generateAuthKey()
    {
        $this->auth_key = Yii::$app->security->generateRandomString();
    }
}

controllers/GroupController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Group;
use app\models\GroupSearch;
use app\models\Student;
use yii\web\Controller;
use yii\web\Response;
use yii\web\NotFoundHttpException;
use yii\web\ForbiddenHttpException;
use yii\data\ActiveDataProvider;

/**
 * GroupController implements the CRUD actions for Group model.
 */
class GroupController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors(){
        return [
            'access' => [
                'class' => \yii\filters\AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['index', 'view', 'create', 'update', 'delete', 'restore'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
        ];
    }

    /**
     * Отображает список групп
     *
     * @return string
     * @throws ForbiddenHttpException
     */
    public function actionIndex()
    {
        if (!Yii::$app->user->can('listGroups')) {
            throw new ForbiddenHttpException('Недостаточно прав');
        }
        $searchModel = new GroupSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Отображает группу по id
     *
     * @param integer $id
     * @return string
     * @throws NotFoundHttpException|ForbiddenHttpException
     */
    public function actionView($id)
    {
        $model = $this->findModel($id);
        if (!Yii::$app->user->can('viewGroup', ['group' => $model])) {
            throw new ForbiddenHttpException('Недостаточно прав');
        }
        $dataGroupStudents = new ActiveDataProvider([
            'query' => Student::find()->where(['group_id' => $id]),
        ]);

        return $this->render('view', [
            'model' => $model,
            'dataGroupStudents' => $dataGroupStudents,
        ]);
    }

    /**
     * Создает новую группу
     *
     * @return string|Response
     * @throws \yii\db\Exception|ForbiddenHttpException
     */
    public function actionCreate()
    {
        if (!Yii::$app->user->can('createGroup')) {
            throw new ForbiddenHttpException('Недостаточно прав');
        }
        $model = new Group();
        $dataFreeStudents = new ActiveDataProvider([
            'query' => Student::find()->where(['group_id' => NULL]),
        ]);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            if ($model->setGroups(Yii::$app->request->post('students'), $model->id)) {
                return $this->redirect(['view', 'id' => $model->id]);
            }
        }

        return $this->render('create', [
            'model' => $model,
            'dataFreeStudents' => $dataFreeStudents,
        ]);
    }

    /**
     * Обновляет существующую группу
     *
     * @param integer $id
     * @return string|Response
     * @throws NotFoundHttpException|ForbiddenHttpException
     * @throws \yii\db\Exception
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if (!Yii::$app->user->can('updateGroup')) {
            throw new ForbiddenHttpException('Недостаточно прав');
        }

        $dataGroupStudents = new ActiveDataProvider([
            'query' => Student::find()->where(['group_id' => $id]),
        ]);
        $dataFreeStudents = new ActiveDataProvider([
            'query' => Student::find()->where(['group_id' => NULL]),
        ]);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            if ($model->setGroups(Yii::$app->request->post('studentGroup'), 'null')
                && $model->setGroups(Yii::$app->request->post('newStudent'), $model->id)) {
                return $this->redirect(['view', 'id' => $model->id]);
            }
        }

        return $this->render('update', [
            'model' => $model,
            'dataFreeStudents' => $dataFreeStudents,
            'dataGroupStudents' => $dataGroupStudents,
        ]);
    }

    /**
     * Удаляет группу
     *
     * @return Response
     * @throws NotFoundHttpException|ForbiddenHttpException
     */
    public function actionDelete()
    {
        if (!Yii::$app->user->can('deleteGroup')) {
            throw new ForbiddenHttpException('Недостаточно прав');
        }
        $id = Yii::$app->request->post('id');
        $group = $this->findModel($id);

        if (!$group->deleted) {
            $group->deleted = true;
            if (!$group->save()) {
                Yii::$app->session->setFlash('error', 'Во время удаления произошла ошибка');
            } else {
                Yii::$app->session->setFlash('success', 'Группа успешно удалена');
            }
        }

        return Yii::$app->response->redirect(Yii::$app->request->referrer ? Yii::$app->request->referrer : '/groups');
    }

    /**
     * Восстанавливает группу
     *
     * @return Response
     * @throws NotFoundHttpException|ForbiddenHttpException
     */
    public function actionRestore()
    {
        if (!Yii::$app->user->can('restoreGroup')) {
            throw new ForbiddenHttpException('Недостаточно прав');
        }
        $id = Yii::$app->request->post('id');
        $group = $this->findModel($id);

        if ($group->deleted) {
            $group->deleted = false;
            if (!$group->save()) {
                Yii::$app->session->setFlash('error', 'Во время восстановления произошла ошибка');
            } else {
                Yii::$app->session->setFlash('success', 'Группа успешно восстановлена');
            }
        }

        return Yii::$app->response->redirect(Yii::$app->request->referrer ? Yii::$app->request->referrer : '/groups');
    }

    /**
     * Ищет группу по id
     *
     * @param integer $id
     * @return Group
     * @throws NotFoundHttpException
     */
    protected function findModel($id)
    {
        if (($model = Group::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('Страница не найдена.');
    }
}

controllers/UserController.php
<?php

namespace app\controllers;

use app\models\User;
use app\models\UserSearch;
use app\models\UserForm;
use yii\data\ActiveDataProvider;
use yii\web\NotFoundHttpException;
use yii\web\ForbiddenHttpException;
use yii\web\Response;
use Yii;

/**
 * Управляет работой с пользователями
 *
 * @package app\controllers
 */
class UserController extends \yii\web\Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors(){
        return [
            'access' => [
                'class' => \yii\filters\AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['index', 'view', 'create', 'update', 'delete', 'restore'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
        ];
    }

    /**
     * Отображает список пользователей
     *
     * @return string
     * @throws ForbiddenHttpException
     */
    public function actionIndex()
    {
        if (!Yii::$app->user->can('listUsers')) {
            throw new ForbiddenHttpException('Недостаточно прав');
        }
        $searchModel = new UserSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', compact('dataProvider', 'searchModel'));
    }

    /**
     * Отображает страницу создания пользователя
     *
     * @return string|Response
     * @throws \yii\base\Exception
     */
    public function  actionCreate()
    {
        if (!Yii::$app->user->can('createUser')) {
            throw new ForbiddenHttpException('Недостаточно прав');
        }
        $userForm = new UserForm(['scenario' => UserForm::SCENARIO_CREATE]);
        $userForm->defaultType();
        if ($userForm->load(Yii::$app->request->post()) && $userForm->create()) {
            Yii::$app->session->setFlash('success', 'Пользователь успешно создан');
            return Yii::$app->response->redirect('/users');
        }
        return $this->render('create', ['userForm' => $userForm]);
    }

    /**
     * Отображает страницу с информацией о пользователе
     *
     * @param $id
     * @return string
     * @throws ForbiddenHttpException|NotFoundHttpException
     */
    public function actionView($id)
    {
        $model = $this->findModel($id);

        if (!Yii::$app->user->can('viewUser', ['user' => $model])) {
            throw new ForbiddenHttpException('Недостаточно прав');
        }
        $dataProvider = null;

        if ($model->type == 'student') {
            $dataProvider = new ActiveDataProvider([
                'query' => $model->students->getAttendances()
            ]);
        }


        return $this->render('view', [
            'model' => $model,
            'dataProvider' => $dataProvider
        ]);
    }

    /**
     * Отображает страницу редактирования пользователя
     *
     * @param $id
     * @return string|Response
     * @throws \yii\base\Exception
     */
    public function actionUpdate($id)
    {
        $userForm = new UserForm(['id' => $id, 'scenario' => UserForm::SCENARIO_UPDATE]);
        if (!Yii::$app->user->can('updateUser', ['user' => $userForm])) {
            throw new ForbiddenHttpException('Недостаточно прав');
        }
        if ($userForm->load(Yii::$app->request->post()) && $userForm->update()) {
            Yii::$app->session->setFlash('success', 'Пользователь успешно изменен');
            return Yii::$app->response->redirect("/user/$id");
        }

        return $this->render('update', ['userForm' => $userForm]);
    }

    /**
     * Удаляет пользователя
     *
     * @return Response
     * @throws ForbiddenHttpException|NotFoundHttpException
     */
    public function actionDelete()
    {
        if (!Yii::$app->user->can('deleteUser')) {
            throw new ForbiddenHttpException('Недостаточно прав');
        }
        $id = Yii::$app->request->post('id');
        $user = $this->findModel($id);

        if (!$user->deleted) {
            $user->deleted = true;
            if (!$user->save()) {
                Yii::$app->session->setFlash('error', 'Во время удаления произошла ошибка');
            } else {
                Yii::$app->session->setFlash('success', 'Пользователь успешно удален');
            }
        }

        return Yii::$app->response->redirect(Yii::$app->request->referrer ? Yii::$app->request->referrer : '/users');
    }

    /**
     * Восстанавливает пользователя
     *
     * @return Response
     * @throws ForbiddenHttpException|NotFoundHttpException
     */
    public function actionRestore()
    {
        if (!Yii::$app->user->can('restoreUser')) {
            throw new ForbiddenHttpException('Недостаточно прав');
        }
        $id = Yii::$app->request->post('id');
        $user = $this->findModel($id);

        if ($user->deleted) {
            $user->deleted = false;
            if (!$user->save()) {
                Yii::$app->session->setFlash('error', 'Во время восстановления произошла ошибка');
            } else {
                Yii::$app->session->setFlash('success', 'Пользователь успешно восстановлен');
            }
        }

        return Yii::$app->response->redirect(Yii::$app->request->referrer ? Yii::$app->request->referrer : '/users');
    }


    /**
     * Ищет пользователя по id
     *
     * @param integer $id
     * @return User
     * @throws NotFoundHttpException
     */
    protected function findModel($id)
    {
        if (($model = User::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('Страница не найдена.');
    }
}

views/user/_form.php
<?php

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

/* @var $userForm app\models\User */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $new boolean */
?>

<div class="user-form">
    <?php $form = ActiveForm::begin(['layout' => 'horizontal']); ?>

    <?= $form->field($userForm, 'nowUsername')->hiddenInput()->label(false) ?>

    <?= $form->field($userForm, 'username')->textInput(['autofocus' => true]) ?>

    <?= $form->field($userForm, 'password')->passwordInput() ?>

    <?= $form->field($userForm, 'repeatPassword')->passwordInput() ?>

    <?= $form->field($userForm, 'lastName')->textInput()?>

    <?= $form->field($userForm, 'firstName')->textInput()?>

    <?= $form->field($userForm, 'middleName')->textInput()?>

    <?= $new ? $form->field($userForm, 'type')->radioList(['student' => 'Студент', 'educator' => 'Преподаватель']) : $form->field($userForm, 'type')->hiddenInput()->label(false) ?>

    <?= Html::submitButton('Сохранить', ['class' => 'btn btn-primary', 'name' => 'sign-up-button']) ?>

    <?php ActiveForm::end(); ?>
</div>

views/user/create.php
<?php

/* @var $userForm app\models\UserForm */
/* @var $this yii\web\View */

$this->title = 'Новый пользователь';
$this->params['breadcrumbs'][] = ['label' => 'Пользователи', 'url' => ['/users']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-sign-up">
    <div class="row">
        <div class="col-lg-5">
            <?= $this->render('_form', [
                'userForm' => $userForm,
                'new' => true,
            ])?>
        </div>
    </div>
</div>

views/user/index.php
<?php

use yii\grid\GridView;
use yii\helpers\Url;
use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $searchModel app\models\UserSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Пользователи';
$this->params['breadcrumbs'][] = $this->title;
?>

<?= Html::a('Создать', 'user/create', ['class' => 'btn btn-lg btn-success'])?>

<?= GridView::widget([
    'dataProvider' => $dataProvider,
    'filterModel' => $searchModel,
    'rowOptions' => function ($data) {
        if ($data['deleted'])
        {
            return ['class'=>'danger'];
        }
    },
    'columns' => [
        [
            'class' => 'yii\grid\SerialColumn',
            'headerOptions' => ['width' => '30'],
        ],
        'fullName',
        [
            'attribute' => 'type',
            'value' => function ($data) {
                if ($data->type == 'student') {
                    return 'Студент';
                }
                else if ($data->type == 'educator') {
                    return 'Преподаватель';
                }
            },
            'filter' => Html::activeDropDownList(
                $searchModel,
                'type',
                [
                    'student' => 'Студенты',
                    'educator' => 'Преподаватели'
                ],
                [
                    'class'=>'form-control',
                    'prompt' => 'Все пользователи'
                ]
            ),
        ],
        [
            'class' => 'yii\grid\ActionColumn',
            'header'=>'Действия',
            'headerOptions' => ['width' => '80'],
            'template' => (Yii::$app->user->can('viewUser') ? '{view} ' : '')
                . (Yii::$app->user->can('updateUser') ? '{update} ' : ' ')
                . (Yii::$app->user->can('deleteUser') ? '{delete}' : ''),
            'buttons' => [
                'delete' => function ($url, $model) {
                    return Html::a('<span class="glyphicon glyphicon-trash"></span>', Url::to(['user/delete']), [
                        'data' => [
                            'confirm' => 'Вы действительно хотите удалить пользователя?',
                            'method' => 'post',
                            'params' => [
                                'id' => $model->id,
                            ],
                        ],
                    ]);
                },
            ],
        ],
    ],
]) ?>

views/user/update.php
<?php

/* @var $userForm app\models\UserForm */
/* @var $this yii\web\View */

$this->title = 'Изменение пользователя: ' . $userForm->nowUsername;
$this->params['breadcrumbs'][] = ['label' => 'Пользователи', 'url' => ['/users']];
$this->params['breadcrumbs'][] = ['label' => $userForm->nowUsername, 'url' => ['view', 'id' => $userForm->id]];
$this->params['breadcrumbs'][] = 'Изменение';
?>
<div class="site-sign-up">
    <div class="row">
        <div class="col-lg-5">
            <?= $this->render('_form', [
                'userForm' => $userForm,
                'new' => false,
            ])?>
        </div>
    </div>
</div>

views/user/view.php
<?php

/** @var $model app\models\User */
/** @var $dataProvider \yii\data\ActiveDataProvider */

use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\DetailView;
use yii\grid\GridView;

$this->title = $model->username;
Yii::$app->user->can('listUsers') ? $this->params['breadcrumbs'][] = ['label' => 'Пользователи', 'url' => ['/users']] : null;
$this->params['breadcrumbs'][] = $this->title;
?>

<p>
    <?= $model->deleted ? Html::tag('h3', 'Пользователь удален', ['style' => ['color' => 'red']])  : '' ?>
    <?= Yii::$app->user->can('updateUser', ['user' => $model]) ?
            Html::a('Редактировать', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) : '' ?>
    <?= $model->deleted ? (
        Yii::$app->user->can('restoreUser') ? (
            Html::a('Восстановить', 'restore', [
                'class' => 'btn btn-success',
                'data' => [
                    'confirm' => 'Вы действительно хотите восстановить пользователя?',
                    'method' => 'post',
                    'params' => [
                        'id' => $model->id,
                    ],
                ],
            ])
        ) : '' ) : (
        Yii::$app->user->can('deleteUser') ? (
            Html::a('Удалить', 'delete', [
                'class' => 'btn btn-danger',
                'data' => [
                    'confirm' => 'Вы действительно хотите удалить пользователя?',
                    'method' => 'post',
                    'params' => [
                        'id' => $model->id,
                    ],
                ],
            ])
        ) : '' ) ?>
</p>
<?= DetailView::widget([
    'model' => $model,
    'attributes' => [
        'id',
        'username',
        [
            'label' => 'Тип пользователя',
            'value' => function ($model) {
                if ($model->type == 'student') {
                    return 'Студент';
                } else if ($model->type == 'educator') {
                    return 'Преподаватель';
                } else {
                    return 'Администратор';
                }
            },
        ],
        $model->type != 'admin' ? 'fullName' : ['visible' => false],
        $model->type == 'student' ? [
            'label' => 'Группа',
            'value' => $model->students->group_id ? Html::a($model->students->groups->name, Url::to(['group/view', 'id' => $model->students->group_id])) : '',
            'format' => 'raw'
        ] : ['visible' => false]
    ],
]) ?>

<?php if ($model->type == 'student') : ?>
    <?php if (Yii::$app->user->can('viewAttendance', ['user' => $model])) :?>
        <h3>Посещаемость</h3>
        <?= GridView::widget([
            'dataProvider' => $dataProvider,
            'columns' => [
                ['class' => 'yii\grid\SerialColumn'],
                'date',
                [
                    'attribute' => 'visited',
                    'value' => function ($data) {
                        if ($data->visited) {
                            return 'Был';
                        }
                        return 'Не был';
                    },
                ],
            ]
        ]) ?>
    <?php endif; ?>
<?php endif; ?>