models/Course.php
<?php

namespace app\models;

/**
 * This is the model class for table "courses".
 *
 * @property int $id
 * @property string $name
 * @property int $educator_id
 * @property bool $deleted
 *
 * @property Educator $educators
 * @property Group[] $groups
 */
class Course extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'courses';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['name', 'educator_id'], 'required'],
            [['educator_id'], 'integer'],
            [['name'], 'string', 'max' => 100],
            [['educator_id'], 'exist', 'skipOnError' => true, 'targetClass' => Educator::className(), 'targetAttribute' => ['educator_id' => 'id']],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Название курса',
            'educator_id' => 'Преподаватель',
            'fullName' => 'ФИО',
        ];
    }

    /**
     * Возвращает кол-во записей
     *
     * @param null $params
     * @return int|string
     */
    public static function getCount($params = null)
    {
        return static::find()->Where($params)->count();
    }

    /**
     * Возвращает ФИО
     *
     * @return string
     */
    public function getFullName()
    {
        return $this->educators->getFullName();
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getEducators()
    {
        return $this->hasOne(Educator::className(), ['id' => 'educator_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getGroups()
    {
        return $this->hasMany(Group::className(), ['course_id' => 'id']);
    }
}

controllers/CourseController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Course;
use app\models\CourseSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\web\ForbiddenHttpException;
use yii\web\Response;

/**
 * Управляет работой с курсами
 *
 * @package app\controllers
 */
class CourseController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors(){
        return [
            'access' => [
                'class' => \yii\filters\AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['index', 'view', 'create', 'update', 'delete', 'restore'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
        ];
    }

    /**
     * Отображает список курсов
     *
     * @return string
     * @throws ForbiddenHttpException
     */
    public function actionIndex()
    {
        if (!Yii::$app->user->can('listCourses')) {
            throw new ForbiddenHttpException('Недостаточно прав');
        }
        $searchModel = new CourseSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', compact('searchModel','dataProvider'));
    }

    /**
     * Отображает страницу просмотра курса
     *
     * @param integer $id
     * @return string
     * @throws NotFoundHttpException|ForbiddenHttpException
     */
    public function actionView($id)
    {
        $model = $this->findModel($id);
        if (!Yii::$app->user->can('viewCourse')) {
            throw new ForbiddenHttpException('Недостаточно прав');
        }
        return $this->render('view', [
            'model' => $model,
        ]);
    }

    /**
     * Отображает страницу создания курса
     *
     * @return string|Response
     * @throws ForbiddenHttpException
     */
    public function actionCreate()
    {
        if (!Yii::$app->user->can('createCourse')) {
            throw new ForbiddenHttpException('Недостаточно прав');
        }
        $model = new Course();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Отображает страницу редактирования курса
     *
     * @param integer $id
     * @return string|Response
     * @throws NotFoundHttpException|ForbiddenHttpException
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if (!Yii::$app->user->can('updateCourse')) {
            throw new ForbiddenHttpException('Недостаточно прав');
        }
        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Удаляет курс
     *
     * @return Response
     * @throws NotFoundHttpException|ForbiddenHttpException
     */
    public function actionDelete()
    {
        if (!Yii::$app->user->can('deleteCourse')) {
            throw new ForbiddenHttpException('Недостаточно прав');
        }
        $id = Yii::$app->request->post('id');
        $course = $this->findModel($id);

        if (!$course->deleted) {
            $course->deleted = true;
            if (!$course->save()) {
                Yii::$app->session->setFlash('error', 'Во время удаления произошла ошибка');
            } else {
                Yii::$app->session->setFlash('success', 'Курс успешно удален');
            }
        }

        return Yii::$app->response->redirect(Yii::$app->request->referrer ? Yii::$app->request->referrer : '/courses');
    }

    /**
     * Восстанавливает курс
     *
     * @return Response
     * @throws NotFoundHttpException|ForbiddenHttpException
     */
    public function actionRestore()
    {
        if (!Yii::$app->user->can('restoreCourse')) {
            throw new ForbiddenHttpException('Недостаточно прав');
        }
        $id = Yii::$app->request->post('id');
        $group = $this->findModel($id);

        if ($group->deleted) {
            $group->deleted = false;
            if (!$group->save()) {
                Yii::$app->session->setFlash('error', 'Во время восстановления произошла ошибка');
            } else {
                Yii::$app->session->setFlash('success', 'Курс успешно восстановлен');
            }
        }

        return Yii::$app->response->redirect(Yii::$app->request->referrer ? Yii::$app->request->referrer : '/courses');
    }

    /**
     * Ищет курс по id
     *
     * @param integer $id
     * @return Course
     * @throws NotFoundHttpException
     */
    protected function findModel($id)
    {
        if (($model = Course::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('Страница не найдена.');
    }
}

controllers/UserController.php
<?php

namespace app\controllers;

use app\models\User;
use app\models\UserSearch;
use app\models\UserForm;
use yii\data\ActiveDataProvider;
use yii\web\NotFoundHttpException;
use yii\web\ForbiddenHttpException;
use yii\web\Response;
use Yii;

/**
 * Управляет работой с пользователями
 *
 * @package app\controllers
 */
class UserController extends \yii\web\Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors(){
        return [
            'access' => [
                'class' => \yii\filters\AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['index', 'view', 'create', 'update', 'delete', 'restore'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
        ];
    }

    /**
     * Отображает список пользователей
     *
     * @return string
     * @throws ForbiddenHttpException
     */
    public function actionIndex()
    {
        if (!Yii::$app->user->can('listUsers')) {
            throw new ForbiddenHttpException('Недостаточно прав');
        }
        $searchModel = new UserSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', compact('dataProvider', 'searchModel'));
    }

    /**
     * Отображает страницу создания пользователя
     *
     * @return string|Response
     * @throws \yii\base\Exception
     */
    public function  actionCreate()
    {
        if (!Yii::$app->user->can('createUser')) {
            throw new ForbiddenHttpException('Недостаточно прав');
        }
        $userForm = new UserForm(['scenario' => UserForm::SCENARIO_CREATE]);
        $userForm->defaultType();
        if ($userForm->load(Yii::$app->request->post()) && $userForm->create()) {
            Yii::$app->session->setFlash('success', 'Пользователь успешно создан');
            return Yii::$app->response->redirect('/users');
        }
        return $this->render('create', ['userForm' => $userForm]);
    }

    /**
     * Отображает страницу с информацией о пользователе
     *
     * @param $id
     * @return string
     * @throws ForbiddenHttpException|NotFoundHttpException
     */
    public function actionView($id)
    {
        $model = $this->findModel($id);

        if (!Yii::$app->user->can('viewUser', ['user' => $model])) {
            throw new ForbiddenHttpException('Недостаточно прав');
        }
        $dataProvider = null;

        if ($model->type == 'student') {
            $dataProvider = new ActiveDataProvider([
                'query' => $model->students->getAttendances()
            ]);
        }


        return $this->render('view', [
            'model' => $model,
            'dataProvider' => $dataProvider
        ]);
    }

    /**
     * Отображает страницу редактирования пользователя
     *
     * @param $id
     * @return string|Response
     * @throws \yii\base\Exception
     */
    public function actionUpdate($id)
    {
        $userForm = new UserForm(['id' => $id, 'scenario' => UserForm::SCENARIO_UPDATE]);
        if (!Yii::$app->user->can('updateUser', ['user' => $userForm])) {
            throw new ForbiddenHttpException('Недостаточно прав');
        }
        if ($userForm->load(Yii::$app->request->post()) && $userForm->update()) {
            Yii::$app->session->setFlash('success', 'Пользователь успешно изменен');
            return Yii::$app->response->redirect("/user/$id");
        }

        return $this->render('update', ['userForm' => $userForm]);
    }

    /**
     * Удаляет пользователя
     *
     * @return Response
     * @throws ForbiddenHttpException|NotFoundHttpException
     */
    public function actionDelete()
    {
        if (!Yii::$app->user->can('deleteUser')) {
            throw new ForbiddenHttpException('Недостаточно прав');
        }
        $id = Yii::$app->request->post('id');
        $user = $this->findModel($id);

        if (!$user->deleted) {
            $user->deleted = true;
            if (!$user->save()) {
                Yii::$app->session->setFlash('error', 'Во время удаления произошла ошибка');
            } else {
                Yii::$app->session->setFlash('success', 'Пользователь успешно удален');
            }
        }

        return Yii::$app->response->redirect(Yii::$app->request->referrer ? Yii::$app->request->referrer : '/users');
    }

    /**
     * Восстанавливает пользователя
     *
     * @return Response
     * @throws ForbiddenHttpException|NotFoundHttpException
     */
    public function actionRestore()
    {
        if (!Yii::$app->user->can('restoreUser')) {
            throw new ForbiddenHttpException('Недостаточно прав');
        }
        $id = Yii::$app->request->post('id');
        $user = $this->findModel($id);

        if ($user->deleted) {
            $user->deleted = false;
            if (!$user->save()) {
                Yii::$app->session->setFlash('error', 'Во время восстановления произошла ошибка');
            } else {
                Yii::$app->session->setFlash('success', 'Пользователь успешно восстановлен');
            }
        }

        return Yii::$app->response->redirect(Yii::$app->request->referrer ? Yii::$app->request->referrer : '/users');
    }


    /**
     * Ищет пользователя по id
     *
     * @param integer $id
     * @return User
     * @throws NotFoundHttpException
     */
    protected function findModel($id)
    {
        if (($model = User::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('Страница не найдена.');
    }
}

views/course/_form.php
<?php

use yii\helpers\Html;
use yii\helpers\ArrayHelper;
use yii\widgets\ActiveForm;
use app\models\Educator;

/* @var $this yii\web\View */
/* @var $model app\models\Course */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="course-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'name')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'educator_id')->dropDownList(ArrayHelper::map(Educator::find()->all(), 'id', function ($data) {
        return $data->getFullName();
    })) ?>

    <div class="form-group">
        <?= Html::submitButton('Сохранить', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/course/create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Course */

$this->title = 'Новый курс';
$this->params['breadcrumbs'][] = ['label' => 'Курсы', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="course-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="col-lg-3">
        <?= $this->render('_form', ['model' => $model,]) ?>
    </div>
</div>

views/course/index.php
<?php

use yii\helpers\Url;
use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel app\models\CourseSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Курсы';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="course-index">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Yii::$app->user->can('createCourse') ? Html::a('Создать курс', ['create'], ['class' => 'btn btn-success']) : '' ?>
    </p>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'rowOptions' => function ($model) {
            if ($model->deleted)
            {
                return ['class' => 'danger'];
            }
        },
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],
            'id',
            'name',
            'fullName',
            [
                'class' => 'yii\grid\ActionColumn',
                'header'=>'Действия',
                'headerOptions' => ['width' => '80'],
                'template' => (Yii::$app->user->can('viewCourse') ? '{view} ' : '')
                    . (Yii::$app->user->can('updateCourse') ? '{update} ' : ' ')
                    . (Yii::$app->user->can('deleteCourse') ? '{delete}' : ''),
                'buttons' => [
                    'delete' => function ($url, $model) {
                        return Html::a('<span class="glyphicon glyphicon-trash"></span>', Url::to(['course/delete']), [
                            'data' => [
                                'confirm' => 'Вы действительно хотите удалить курс?',
                                'method' => 'post',
                                'params' => [
                                    'id' => $model->id,
                                ],
                            ],
                        ]);
                    },
                ],
            ],
        ],
    ]); ?>


</div>

views/course/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Course */

$this->title = 'Редактирование курса: ' . $model->name;
$this->params['breadcrumbs'][] = ['label' => 'Курсы', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->name, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Редактирование';
?>
<div class="course-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="col-lg-3">
        <?= $this->render('_form', ['model' => $model]) ?>
    </div>

</div>

views/course/view.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\Course */

$this->title = $model->name;
Yii::$app->user->can('listCourses') ? $this->params['breadcrumbs'][] = ['label' => 'Курсы', 'url' => ['index']] : null;
$this->params['breadcrumbs'][] = $this->title;
\yii\web\YiiAsset::register($this);
?>
<div class="course-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= $model->deleted ? Html::tag('h3', 'Курс удален', ['style' => ['color' => 'red']])  : '' ?>
        <?= Yii::$app->user->can('updateCourse') ? (
                Html::a('Редактировать', ['update', 'id' => $model->id], ['class' => 'btn btn-primary'])
            ) : '' ?>
        <?= $model->deleted ? (
            Yii::$app->user->can('restoreCourse') ? (
                Html::a('Восстановить', 'restore', [
                    'class' => 'btn btn-success',
                    'data' => [
                        'confirm' => 'Вы действительно хотите восстановить курс?',
                        'method' => 'post',
                        'params' => [
                            'id' => $model->id,
                        ],
                    ],
                ])
            ) : '') : (
            Yii::$app->user->can('deleteCourse') ? (
                Html::a('Удалить', 'delete', [
                    'class' => 'btn btn-danger',
                    'data' => [
                        'confirm' => 'Вы действительно хотите удалить курс?',
                        'method' => 'post',
                        'params' => [
                            'id' => $model->id,
                        ],
                    ],
                ])
            ) : '' ) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'name',
            [
                'label' => 'Преподаватель',
                'value' => Html::a($model->educators->getFullName(), Url::to(['user/view', 'id' => $model->educators->user_id])),
                'format' => 'raw'
            ],
        ],
    ]) ?>

</div>